# Generated by Django 5.2 on 2025-05-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_author_alter_category_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userblog',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
